# GoReleaser configuration for ClippingKK CLI
version: 2

project_name: ck-cli

before:
  hooks:
    # Clean up any previous builds
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  - main: ./cmd/ck-cli
    binary: ck-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Build flags
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
    # Ignore specific combinations that don't make sense
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\(.+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\(.+\))??!?:.+$'
      order: 3
    - title: 'Others'
      order: 999

release:
  github:
    owner: clippingkk
    name: cli
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## ClippingKK CLI {{.Tag}}
    
    Parse Amazon Kindle clippings and sync to ClippingKK service.
    
    ### Installation
    
    Download the appropriate binary for your platform from the assets below.
    
    ### What's Changed
  footer: |
    **Full Changelog**: https://github.com/clippingkk/cli/compare/{{ .PreviousTag }}...{{ .Tag }}

# Package managers
brews:
  - name: ck-cli
    repository:
      owner: clippingkk
      name: homebrew-ck-cli
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/clippingkk/cli"
    description: "Parse Amazon Kindle clippings and sync to ClippingKK service"
    license: "MIT"
    test: |
      system "#{bin}/ck-cli --version"
    install: |
      bin.install "ck-cli"

nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    id: packages
    homepage: https://github.com/clippingkk/cli
    description: |-
      Parse Amazon Kindle clippings and sync to ClippingKK service.
      
      ClippingKK CLI is a tool that parses Amazon Kindle's "My Clippings.txt" 
      file into structured JSON format and can sync highlights to the 
      ClippingKK web service for cloud storage.
    maintainer: Annatar He <annatar.he+ck.cli@gmail.com>
    license: MIT
    vendor: ClippingKK
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/ck-cli/copyright
        file_info:
          mode: 0644
      - src: ./README.md
        dst: /usr/share/doc/ck-cli/README.md
        file_info:
          mode: 0644
    formats:
    - apk
    - deb
    - rpm
    dependencies:
      - ca-certificates
    recommends:
      - git

aurs:
  - name: ck-cli-bin
    homepage: https://github.com/clippingkk/cli
    description: "Parse Amazon Kindle clippings and sync to ClippingKK service"
    maintainers:
      - 'Annatar He <annatar.he+ck.cli@gmail.com>'
    license: MIT
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/ck-cli-bin.git'
    depends:
      - ca-certificates
    package: |-
      # bin
      install -Dm755 "./ck-cli" "${pkgdir}/usr/bin/ck-cli"
      
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/ck-cli/LICENSE"
      
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

dockers:
  - image_templates:
      - "ghcr.io/clippingkk/ck-cli:{{ .Tag }}-amd64"
      - "ghcr.io/clippingkk/ck-cli:v{{ .Major }}-amd64"
      - "ghcr.io/clippingkk/ck-cli:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/clippingkk/ck-cli:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/clippingkk/ck-cli:{{ .Tag }}-arm64"
      - "ghcr.io/clippingkk/ck-cli:v{{ .Major }}-arm64"
      - "ghcr.io/clippingkk/ck-cli:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/clippingkk/ck-cli:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/clippingkk/ck-cli:{{ .Tag }}"
    image_templates:
      - "ghcr.io/clippingkk/ck-cli:{{ .Tag }}-amd64"
      - "ghcr.io/clippingkk/ck-cli:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/clippingkk/ck-cli:v{{ .Major }}"
    image_templates:
      - "ghcr.io/clippingkk/ck-cli:v{{ .Major }}-amd64"
      - "ghcr.io/clippingkk/ck-cli:v{{ .Major }}-arm64"
  - name_template: "ghcr.io/clippingkk/ck-cli:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/clippingkk/ck-cli:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/clippingkk/ck-cli:v{{ .Major }}.{{ .Minor }}-arm64"
  - name_template: "ghcr.io/clippingkk/ck-cli:latest"
    image_templates:
      - "ghcr.io/clippingkk/ck-cli:latest-amd64"
      - "ghcr.io/clippingkk/ck-cli:latest-arm64"