# GoReleaser configuration for ClippingKK CLI
version: 2

project_name: ck-cli

before:
  hooks:
    # Clean up any previous builds
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  - main: ./cmd/ck-cli
    binary: ck-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Build flags
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
    # Ignore specific combinations that don't make sense
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\(.+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\(.+\))??!?:.+$'
      order: 3
    - title: 'Others'
      order: 999

release:
  github:
    owner: clippingkk
    name: cli
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## ClippingKK CLI {{.Tag}}
    
    Parse Amazon Kindle clippings and sync to ClippingKK service.
    
    ### Installation
    
    Download the appropriate binary for your platform from the assets below.
    
    ### What's Changed
  footer: |
    **Full Changelog**: https://github.com/clippingkk/cli/compare/{{ .PreviousTag }}...{{ .Tag }}

