before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/cli.go
    id: cli
    binary: clippingkk-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

archives:
  -
    id: cli
    format: binary
    files:
      - clippingkk-cli
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
