on: [pull_request]
name: test and lint pull requests
jobs:
  test:
    name: test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Run tests with coverage
        run: go test -timeout 3m -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_CLI_TOKEN }}
      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Run benchmarks
        run: go test -bench=. ./...
