name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - run: git fetch --force --tags
      
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      
      - name: Test
        run: go test -timeout 3m -coverprofile=coverage.txt -covermode=atomic ./...
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_CLI_TOKEN }}
      
      - uses: goreleaser/goreleaser-action@v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          VERSION: ${{ steps.release.outputs.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUILL_SIGN_P12: ${{ secrets.QUILL_SIGN_P12 }}
          QUILL_SIGN_PASSWORD: ${{ secrets.QUILL_SIGN_PASSWORD }}
          QUILL_NOTARY_KEY: ${{ secrets.QUILL_NOTARY_KEY }}
          QUILL_NOTARY_KEY_ID: ${{ secrets.QUILL_NOTARY_KEY_ID }}
          QUILL_NOTARY_ISSUER: ${{ secrets.QUILL_NOTARY_ISSUER }}