# .github/workflows/release.yml
name: release-artifacts

on:
  push:
    branches: [feat/ci-sign]
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    # runs-on: ubuntu-latest
    runs-on: macos-11.0
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            archive: zip
          - target: aarch64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        with:
          UPLOAD_MODE: none
        env:
          APPLE_DEVELOPER_CERT: ${{ secrets.APPLE_DEVELOPER_CERT }}
          APPLE_DEVELOPER_CERT_PWD: ${{ secrets.APPLE_DEVELOPER_CERT_PWD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          POST_BUILD: ./codesign.apple.bash
